language: cpp
script: cmake
sudo: required
dist: trusty

before_install:
    - wget https://www.libsdl.org/release/SDL2-2.0.7.tar.gz -O SDL2-2.0.7.tar.gz
    - tar -xzvf SDL2-2.0.7.tar.gz
    - wget https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.0.1.tar.gz
    - tar -xzvf SDL2_net-2.0.1.tar.gz
    - wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz
    - tar -xzvf SDL2_mixer-2.0.4.tar.gz
    

install:
    - (cd SDL2-2.0.7 && ./configure && make && sudo make install && cd ..)
    - (cd SDL2_net-2.0.1 && ./configure && make && sudo make install && cd ..)
    - (cd SDL2_mixer-2.0.4 && ./configure && make && sudo make install && cd ..)

matrix:
     include:
        # Linux x64 gcc
        - os: linux
          compiler: gcc

        # macOS
        - os: osx
          compiler: clang

        # Linux i686 gcc
        - os: linux
          compiler: gcc
          env: host=i686-linux-gnu


script:
    - cmake -G "Unix Makefiles" -DCMAKE_SOURCE_DIR="./"
    - make